spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  cloud:
    gcp:
      storage:
        credentials:
          location: ""
        project-id: ""
        bucket: ""

  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/
    username : ""
    password : ""
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: 
#    username: ""
#    password: ""


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto : update
#      ddl-auto: create
#      ddl-auto: none
      show-sql: true # DDL 출력
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

OPENVIDU_URL:

OPENVIDU_SECRET:


oauth:
  naver:
    secret: 
    client-id: 
    url:
      auth: 
      api: 
jwt:
  secret-key: 
